clang-tidy: Add missing 'override' specifiers
Fixes for clang-tidy errors

'''
/include/error_monitors/err_pin_timeout_monitor.hpp:40:10: error:
   'logEvent' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
/include/error_monitors/ierr_monitor.hpp:47:10: error:
   'logEvent' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
'''

Change-Id: Ic0b34e258d3996251f8f236a3840c1cc7f4e570a
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>