clang-tidy: Add missing header for sd_journal_send
Resolved build error caused by missing <systemd/sd-journal.h> include
in BaseMonitor. The sd_journal_send function requires this header
to compile correctly when logging to the systemd journal.

'''
include/error_monitors/err_pin_timeout_monitor.hpp:40:10: error:
 'logEvent' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
'''

Change-Id: I35f22b0edbb16a0cc41e29028346047b060c27cf
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>